#!/bin/bash

# Script to setup my ubuntu operting system settings after a new install

function print_usage() {
    echo "usage: sudo ./setup <desktop|laptop> [work] [wirelessfix]"
}

# Must be run as root
if [ "$(id -u)" -ne 0 ]; then 
    echo "Please run as root"
    print_usage
    exit 1
fi

LAUNCHER_PROGRAMS="['application://org.gnome.Nautilus.desktop', 'application://notepadqq.desktop', 'unity://running-apps', 'application://google-chrome.desktop', 'unity://expo-icon', 'unity://devices']"

DESKTOP=false
WORK=false
WIRELESSFIX=false

# Read the options
case $1 in
    "desktop")
        echo "Setting up as a desktop"
        DESKTOP=true
        ;;
    "laptop")
        echo "Setting up as a laptop"
        DESKTOP=false        
        ;;
    *)
        print_usage
        exit 1
        ;;
esac

if [ "$2" == "work" ]; then
    echo "For work";
    WORK=true
fi

if [ "$2" == "wirelessfix" -o "$3" == "wirelessfix" ]; then
    echo "And installing a wireless driver fix"
    WIRELESSFIX=true
fi

echo ----------------------------------------------------------------
echo "Starting install in 10 seconds, will reboot after setup. Could take half an hour"
sleep 10s

cd ~ 

# Gather PPAs
#############

apt-get -y install software-properties-common curl
add-apt-repository ppa:lyzardking/ubuntu-make

if [ "$DESKTOP" == "false" ]; then
    # Touchpad indicator
    add-apt-repository -y ppa:atareao/atareao 
fi

# VsCode
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

apt-get update


# Install packages
##################

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
dpkg -i ./google-chrome*.deb
apt-get install -f
rm ./google-chrome*.deb

apt-get -y install \
    apt-transport-https \
    notepadqq \
    code \
    android-tools-fastboot \
    vlc \
    g++ \

# Laptop needs touchpad
if [ "$DESKTOP" == "false" ]; then
    apt-get -y install touchpad-indicator
fi

if [ "$WORK" == "false" ]; then
    apt-get -y install qbittorrent
fi

# Docker
curl -fsSL get.docker.com -o get-docker.sh
sh get-docker.sh

usermod -aG docker $SUDO_USER

# Fix some settings
###################

# If we are on the laptop, make sure that it has a british keyboard on crouton launch
if [ $DESKTOP == false ]; then
    echo "@setxkbmap gb">>~/.config/lxsession/LXDE/autostart
fi

# Add platform tools to my path
echo 'export PATH=$PATH:"$HOME/Android/Sdk/platform-tools"' >> $HOME/.profile

if [ "$DESKTOP" == "true" ]; then
    # Linux log on boot instead of splash screen
    sed -i 's/.*GRUB_CMDLINE_LINUX_DEFAULT.*/GRUB_CMDLINE_LINUX_DEFAULT=""/' /etc/default/grub
    update-grub
fi

apt-get -y install ubuntu-make

umake android ~/.local/share/umake/android/android-studio --accept-license

if [ "$DESKTOP" == "true" ]; then
    # Desktop needs these set for AVD
    apt-get -y install lib32stdc++6 lib32z1
    apt-get -y install libgl1-mesa-dev
    # This fixes the emulator for some reason
    echo "export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1">>$HOME/.profile
fi 

su $SUDO_USER -c "git config --global user.email \"freshollie@gmail.com\""
su $SUDO_USER -c "git config --global user.name \"Oliver Bell\""
su $SUDO_USER -c "git config --global push.default simple"

echo "fs.inotify.max_user_watches=524288" >> /etc/sysctl.conf

# Remove bloat
##############
snap remove firefox
apt-get -y remove --purge libreoffice*
apt-get -y clean
apt-get -y autoremove

reboot
