#!/bin/bash

# Script to setup my ubuntu operting system settings after a new install

function print_usage() {
    echo "usage: sudo ./setup <desktop|laptop> [work] [wirelessfix]"
}

# Must be run as root
if [ "$(id -u)" -ne 0 ]; then 
    echo "Please run as root"
    print_usage
    exit 1
fi

LAUNCHER_PROGRAMS="['application://org.gnome.Nautilus.desktop', 'application://notepadqq.desktop', 'unity://running-apps', 'application://google-chrome.desktop', 'unity://expo-icon', 'unity://devices']"

DESKTOP=false
WORK=false
WIRELESSFIX=false

# Read the options
case $1 in
    "desktop")
        echo "Setting up as a desktop"
        DESKTOP=true
        ;;
    "laptop")
        echo "Setting up as a laptop"
        DESKTOP=false        
        ;;
    *)
        print_usage
        exit 1
        ;;
esac

if [ "$2" == "work" ]; then
    echo "For work";
    WORK=true
fi

if [ "$2" == "wirelessfix" -o "$3" == "wirelessfix" ]; then
    echo "And installing a wireless driver fix"
    WIRELESSFIX=true
fi

echo ----------------------------------------------------------------
echo "Starting install in 10 seconds, will reboot after setup. Could take half an hour"
sleep 10s

cd ~ 

# Gather PPAs
#############

apt-get -y install software-properties-common python-software-properties

# Chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

# Notepad QQ
add-apt-repository -y ppa:notepadqq-team/notepadqq

if [ $DESKTOP == false ]; then
    # Touchpad indicator
    add-apt-repository -y ppa:atareao/atareao 
fi

# F.lux
add-apt-repository -y ppa:nathan-renniewaldock/flux

if [ $WORK == false ]; then
    # Qbittorrent 
    add-apt-repository -y ppa:qbittorrent-team/qbittorrent-stable
fi

# Java
add-apt-repository -y ppa:openjdk-r/ppa

# Android studio and visual-code
add-apt-repository -y ppa:ubuntu-desktop/ubuntu-make

# Don't install spotify or vscode on a laptop
if [ $DESKTOP == true ]; then
    # VsCode
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
    sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

    # Spotify
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
    echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
fi

apt-get update


# Install packages
##################

apt-get -y install google-chrome-stable

apt-get -y install notepadqq

apt-get -y install code

apt-get -y install android-tools-fastboot

# Laptop needs touchpad
if [ $DESKTOP == false ]; then
    apt-get -y install touchpad-indicator
fi

apt-get -y install fluxgui

if [ $WORK == false ]; then
    apt-get -y install qbittorrent
fi

apt-get -y install vlc

apt-get -y install nano

apt-get -y install g++

if [ $DESKTOP == true ]; then 
    # Wallpaper slideshow
    apt-get -y install variety
fi

apt-get -y install curl

# install nodejs
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash
apt-get install -y nodejs

apt-get -y install npm

if [ $DESKTOP == true ]; then
    apt-get -y --allow-unauthenticated install spotify-client 
	apt-get -y install code
fi

if [ $WIRELESSFIX == true ]; then
    # TL-WN823N wireless driver
    apt-get -y install linux-headers-generic build-essential dkms
    
    git clone https://github.com/Mange/rtl8192eu-linux-driver.git

    # Build and install a new driver
    dkms install ./rtl8192eu-linux-driver
    
    git clone https://github.com/pvaret/rtl8192cu-fixes.git
    
    # Stop the old driver
    modprobe -r rtl8xxxu
    
    # Stop the old driver forever
    cp ./rtl8192cu-fixes/blacklist-native-rtl8192.conf /etc/modprobe.d/
fi

# Install java 8
apt-get -y install oracle-java8-installer

# Fix some settings
###################

# If we are on the laptop, make sure that it has a british keyboard on crouton launch
if [ $DESKTOP == false ]; then
    echo "@setxkbmap gb">>~/.config/lxsession/LXDE/autostart
fi

# Add platform tools to my path
echo 'export PATH=$PATH:"$HOME/Android/Sdk/platform-tools"' >> $HOME/.profile

if [ $DESKTOP == true ]; then
    # Update screenshot preferences
    su $SUDO_USER -c "gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot '<Primary>Print'"
    su $SUDO_USER -c "gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot-clip 'Print'"
    su $SUDO_USER -c "gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot '<Primary><Shift>Print'"
    su $SUDO_USER -c "gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot-clip '<Shift>Print'"
    su $SUDO_USER -c "gsettings set org.gnome.settings-daemon.plugins.media-keys window-screenshot '<Primary><Alt>Print'"
    su $SUDO_USER -c "gsettings set org.gnome.settings-daemon.plugins.media-keys window-screenshot-clip '<Alt>Print'"
    
    su $SUDO_USER -c "gsettings set com.canonical.Unity.Launcher favorites \"$LAUNCHER_PROGRAMS\""
    
    #Set the bar to bottom
    su $SUDO_USER -c "gsettings set com.canonical.Unity.Launcher launcher-position Bottom"
    
    # Set as light theme
    su $SUDO_USER -c "gsettings set org.gnome.desktop.interface gtk-theme 'Radiance'"
    su $SUDO_USER -c "gsettings set org.gnome.desktop.interface icon-theme 'ubuntu-mono-light'"
    su $SUDO_USER -c "gsettings set org.gnome.desktop.wm.preferences theme 'Radiance'"
    
    su $SUDO_USER -c "gsettings set com.canonical.Unity always-show-menus true"
    
    su $SUDO_USER -c "gsettings set org.gnome.desktop.peripherals.mouse speed 1.0"
    
    # Linux log on boot instead of splash screen
    sed -i 's/.*GRUB_CMDLINE_LINUX_DEFAULT.*/GRUB_CMDLINE_LINUX_DEFAULT=""/' /etc/default/grub
    update-grub
fi

apt-get -y install ubuntu-make

umake android ~/.local/share/umake/android/android-studio --accept-license

if [ $DESKTOP == true ]; then
    # Desktop needs these set for AVD
    apt-get -y install lib32stdc++6 lib32z1
    apt-get -y install libgl1-mesa-dev
    # This fixes the emulator for some reason
    echo "export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1">>$HOME/.profile
fi 

su $SUDO_USER -c "git config --global user.email \"freshollie@gmail.com\""
su $SUDO_USER -c "git config --global user.name \"Oliver Bell\""
su $SUDO_USER -c "git config --global push.default simple"

# Remove bloat
##############
apt-get -y remove --purge firefox
apt-get -y remove --purge libreoffice*
# remove the amazon icon
echo 'Hidden=true' | cat /usr/share/applications/ubuntu-amazon-default.desktop - > $HOME/.local/share/applications/ubuntu-amazon-default.desktop
apt-get -y clean
apt-get -y autoremove

reboot
